-- Script to populate catch_reports table with comprehensive "What's Biting Where?" data
-- Run this in your Supabase SQL Editor

-- Clear existing data (optional - comment out if you want to keep existing data)
-- DELETE FROM catch_reports;

-- Insert comprehensive catch reports data for "What's Biting Where?"
INSERT INTO catch_reports (
    species, quantity, location_name, spot_name, latitude, longitude, 
    date_caught, time_caught, conditions, bait_used, notes, angler_name, 
    angler_contact, verified, created_at
) VALUES 
-- KwaZulu-Natal Region
(
    'Bronze bream',
    3,
    'Durban',
    'North Pier',
    -29.8587,
    31.0218,
    NOW() - INTERVAL '2 hours',
    '07:30:00',
    'Clear skies, light wind, good visibility',
    'Live prawns',
    'Great morning session! Fish were biting on the incoming tide. Caught 3 good size bream between 40-50cm.',
    'Mike Johnson',
    '082 123 4567',
    true,
    NOW() - INTERVAL '2 hours'
),
(
    'Common / Dusky kob',
    2,
    'Ballito',
    'Thompson Bay',
    -29.5333,
    31.2167,
    NOW() - INTERVAL '4 hours',
    '06:15:00',
    'Overcast, moderate swell, good water clarity',
    'Live shad',
    'Early morning kob action! Two nice fish around 60-70cm. Best time was just before sunrise.',
    'Sarah Wilson',
    '083 987 6543',
    true,
    NOW() - INTERVAL '4 hours'
),
(
    'Black musselcracker',
    1,
    'Umhlanga Rocks',
    'Lighthouse',
    -29.7167,
    31.0833,
    NOW() - INTERVAL '6 hours',
    '05:45:00',
    'Clear conditions, light offshore wind',
    'Red bait',
    'Big cracker! Estimated 8kg. Fought hard for 20 minutes. Released safely.',
    'David Brown',
    '084 555 1234',
    true,
    NOW() - INTERVAL '6 hours'
),
(
    'Elf / Shad',
    8,
    'Scottburgh',
    'Main Beach',
    -30.2833,
    30.7500,
    NOW() - INTERVAL '8 hours',
    '16:30:00',
    'Good swell, clear water, light wind',
    'Small spoons',
    'Shad were running! Caught 8 in about 2 hours. Great for bait or eating.',
    'Lisa Davis',
    '082 444 7890',
    true,
    NOW() - INTERVAL '8 hours'
),
(
    'Spotted grunter',
    2,
    'Richards Bay',
    'Alkantstrand',
    -28.7833,
    32.1000,
    NOW() - INTERVAL '12 hours',
    '14:20:00',
    'Overcast, moderate wind, good water clarity',
    'Live mud prawns',
    'Nice grunter action in the estuary. Both fish around 45cm.',
    'Peter van der Merwe',
    '083 222 3456',
    true,
    NOW() - INTERVAL '12 hours'
),

-- Eastern Cape Region
(
    'Galjoen',
    4,
    'Port Elizabeth',
    'Sardinia Bay',
    -33.9608,
    25.6022,
    NOW() - INTERVAL '3 hours',
    '08:15:00',
    'Clear skies, moderate swell, good visibility',
    'Red bait',
    'Galjoen were active! Caught 4 between 30-40cm. Best spots were the rocky outcrops.',
    'Anna Botha',
    '084 666 7777',
    true,
    NOW() - INTERVAL '3 hours'
),
(
    'Roman',
    3,
    'East London',
    'Nahoon Beach',
    -33.0153,
    27.9116,
    NOW() - INTERVAL '5 hours',
    '07:00:00',
    'Light wind, clear water, good conditions',
    'Live sand prawns',
    'Roman were biting well! Three nice fish around 35-45cm.',
    'Johan Pretorius',
    '082 777 8888',
    true,
    NOW() - INTERVAL '5 hours'
),
(
    'Blacktail',
    6,
    'Jeffreys Bay',
    'Supertubes',
    -34.0489,
    24.9111,
    NOW() - INTERVAL '7 hours',
    '06:30:00',
    'Good swell, clear conditions',
    'Small spoons',
    'Blacktail were running! Caught 6 in about 90 minutes. Great fun on light tackle.',
    'Hendrik van Wyk',
    '083 333 4444',
    true,
    NOW() - INTERVAL '7 hours'
),
(
    'White steenbras',
    2,
    'Port Alfred',
    'Kelly Beach',
    -33.5906,
    26.8910,
    NOW() - INTERVAL '9 hours',
    '15:45:00',
    'Moderate wind, good water clarity',
    'Live bloodworm',
    'Steenbras action! Two nice fish around 50-60cm. Best time was on the outgoing tide.',
    'Maria Ferreira',
    '084 888 9999',
    true,
    NOW() - INTERVAL '9 hours'
),

-- Western Cape Region
(
    'Cape stumpnose',
    5,
    'Cape Town',
    'Muizenberg',
    -33.9249,
    18.4241,
    NOW() - INTERVAL '2 hours',
    '07:45:00',
    'Clear skies, light wind, excellent visibility',
    'Live prawns',
    'Stumpnose were active! Caught 5 between 25-35cm. Best spots were the deeper holes.',
    'Chris de Villiers',
    '082 111 2222',
    true,
    NOW() - INTERVAL '2 hours'
),
(
    'Leervis / Garrick',
    1,
    'Hermanus',
    'Grotto Beach',
    -34.4187,
    19.2345,
    NOW() - INTERVAL '4 hours',
    '06:00:00',
    'Good swell, clear water, light offshore wind',
    'Live shad',
    'Big garrick! Estimated 12kg. Amazing fight! Released safely.',
    'Amanda Botha',
    '083 444 5555',
    true,
    NOW() - INTERVAL '4 hours'
),
(
    'White musselcracker',
    2,
    'Langebaan',
    'Die Plaat',
    -33.1000,
    18.0333,
    NOW() - INTERVAL '6 hours',
    '08:30:00',
    'Clear conditions, moderate wind',
    'Red bait',
    'Cracker action! Two nice fish around 6-8kg. Great fight!',
    'Daniel van der Berg',
    '084 666 7777',
    true,
    NOW() - INTERVAL '6 hours'
),
(
    'Galjoen',
    3,
    'Yzerfontein',
    'Main Beach',
    -33.3500,
    18.1500,
    NOW() - INTERVAL '8 hours',
    '07:15:00',
    'Good swell, clear water',
    'Red bait',
    'Galjoen were biting! Three nice fish between 30-40cm.',
    'Sandra van Rensburg',
    '082 888 0000',
    true,
    NOW() - INTERVAL '8 hours'
),
(
    'Bronze bream',
    4,
    'Paternoster',
    'Tietiesbaai',
    -32.8167,
    17.8833,
    NOW() - INTERVAL '10 hours',
    '06:45:00',
    'Clear skies, light wind',
    'Live prawns',
    'Bream were active! Four nice fish between 35-45cm.',
    'Tom Anderson',
    '083 111 3333',
    true,
    NOW() - INTERVAL '10 hours'
),

-- Northern Cape Region
(
    'Bronze bream',
    2,
    'Port Nolloth',
    'Main Beach',
    -29.2500,
    16.8667,
    NOW() - INTERVAL '5 hours',
    '07:30:00',
    'Clear conditions, light wind',
    'Red bait',
    'Bream action! Two nice fish around 40-50cm.',
    'Patricia Ndlovu',
    '084 222 4444',
    true,
    NOW() - INTERVAL '5 hours'
),
(
    'Galjoen',
    3,
    'Hondeklipbaai',
    'Main Beach',
    -30.3167,
    17.2833,
    NOW() - INTERVAL '7 hours',
    '08:00:00',
    'Good swell, clear water',
    'Red bait',
    'Galjoen were biting! Three nice fish between 30-40cm.',
    'Michael van der Walt',
    '082 444 6666',
    true,
    NOW() - INTERVAL '7 hours'
),

-- Additional Recent Reports (Last 24 hours)
(
    'Common / Dusky kob',
    1,
    'Durban',
    'South Pier',
    -29.8587,
    31.0218,
    NOW() - INTERVAL '1 hour',
    '06:30:00',
    'Early morning, clear conditions',
    'Live shad',
    'Nice kob! Around 65cm. Great fight!',
    'Liam O''Connor',
    '083 666 8888',
    true,
    NOW() - INTERVAL '1 hour'
),
(
    'Black musselcracker',
    1,
    'Ballito',
    'Salt Rock',
    -29.5000,
    31.2333,
    NOW() - INTERVAL '3 hours',
    '07:15:00',
    'Good conditions, clear water',
    'Red bait',
    'Big cracker! Estimated 10kg. Released safely.',
    'Elena van der Berg',
    '084 999 0000',
    true,
    NOW() - INTERVAL '3 hours'
),
(
    'Spotted grunter',
    3,
    'Port Elizabeth',
    'Pollock Beach',
    -33.9608,
    25.6022,
    NOW() - INTERVAL '4 hours',
    '08:00:00',
    'Good conditions, moderate wind',
    'Live mud prawns',
    'Grunter were active! Three nice fish between 40-50cm.',
    'Markus van der Walt',
    '082 111 3333',
    true,
    NOW() - INTERVAL '4 hours'
),
(
    'Elf / Shad',
    5,
    'East London',
    'Orient Beach',
    -33.0153,
    27.9116,
    NOW() - INTERVAL '6 hours',
    '06:45:00',
    'Good swell, clear water',
    'Small spoons',
    'Shad were running! Five nice fish. Great fun!',
    'Andre du Toit',
    '083 444 6666',
    true,
    NOW() - INTERVAL '6 hours'
),
(
    'Cape stumpnose',
    4,
    'Cape Town',
    'Camps Bay',
    -34.8167,
    18.8333,
    NOW() - INTERVAL '8 hours',
    '07:30:00',
    'Clear conditions, light wind',
    'Live prawns',
    'Stumpnose were biting! Four nice fish between 25-35cm.',
    'Willem van der Merwe',
    '084 666 8888',
    true,
    NOW() - INTERVAL '8 hours'
),
(
    'Galjoen',
    2,
    'Hermanus',
    'Voelklip',
    -34.4187,
    19.2345,
    NOW() - INTERVAL '10 hours',
    '08:15:00',
    'Good swell, clear water',
    'Red bait',
    'Galjoen action! Two nice fish between 30-40cm.',
    'Stephan van Niekerk',
    '082 222 4444',
    true,
    NOW() - INTERVAL '10 hours'
),
(
    'Bronze bream',
    3,
    'Langebaan',
    'Kraalbaai',
    -33.1000,
    18.0333,
    NOW() - INTERVAL '12 hours',
    '09:00:00',
    'Good conditions, light wind',
    'Live prawns',
    'Bream were active! Three nice fish between 35-45cm.',
    'Gregory Muller',
    '083 888 0000',
    true,
    NOW() - INTERVAL '12 hours'
),
(
    'White steenbras',
    1,
    'Port Alfred',
    'West Beach',
    -33.5906,
    26.8910,
    NOW() - INTERVAL '14 hours',
    '16:30:00',
    'Good conditions, moderate wind',
    'Live bloodworm',
    'Nice steenbras! Around 55cm. Great fight!',
    'Lucas van der Walt',
    '084 111 3333',
    true,
    NOW() - INTERVAL '14 hours'
),
(
    'Blacktail',
    7,
    'Jeffreys Bay',
    'Boneyards',
    -34.0489,
    24.9111,
    NOW() - INTERVAL '16 hours',
    '06:00:00',
    'Good swell, clear conditions',
    'Small spoons',
    'Blacktail were running! Seven nice fish. Great fun on light tackle.',
    'Daniel van der Merwe',
    '082 444 6666',
    true,
    NOW() - INTERVAL '16 hours'
),
(
    'Roman',
    2,
    'East London',
    'Eastern Beach',
    -33.0153,
    27.9116,
    NOW() - INTERVAL '18 hours',
    '07:45:00',
    'Good conditions, clear water',
    'Live sand prawns',
    'Roman were biting! Two nice fish around 40-50cm.',
    'Jennifer van Rensburg',
    '083 666 8888',
    true,
    NOW() - INTERVAL '18 hours'
),
(
    'Leervis / Garrick',
    1,
    'Hermanus',
    'Die Plaat',
    -34.4187,
    19.2345,
    NOW() - INTERVAL '20 hours',
    '06:30:00',
    'Good swell, clear water',
    'Live shad',
    'Big garrick! Estimated 15kg. Amazing fight! Released safely.',
    'Michael van der Walt',
    '084 999 0000',
    true,
    NOW() - INTERVAL '20 hours'
),
(
    'White musselcracker',
    1,
    'Langebaan',
    'Schaapen Island',
    -33.1000,
    18.0333,
    NOW() - INTERVAL '22 hours',
    '08:45:00',
    'Good conditions, moderate wind',
    'Red bait',
    'Big cracker! Estimated 12kg. Great fight!',
    'Amanda van der Berg',
    '082 111 3333',
    true,
    NOW() - INTERVAL '22 hours'
),
(
    'Cape stumpnose',
    6,
    'Cape Town',
    'Bloubergstrand',
    -33.8000,
    18.4500,
    NOW() - INTERVAL '24 hours',
    '07:00:00',
    'Clear conditions, light wind',
    'Live prawns',
    'Stumpnose were active! Six nice fish between 25-35cm.',
    'Hendrik van Rensburg',
    '083 444 6666',
    true,
    NOW() - INTERVAL '24 hours'
);

-- Verify the data was inserted
SELECT COUNT(*) as total_reports FROM catch_reports;
SELECT location_name, COUNT(*) as count FROM catch_reports GROUP BY location_name ORDER BY count DESC;
SELECT species, COUNT(*) as count FROM catch_reports GROUP BY species ORDER BY count DESC;
SELECT 
    DATE(date_caught) as catch_date,
    COUNT(*) as reports_count
FROM catch_reports 
GROUP BY DATE(date_caught) 
ORDER BY catch_date DESC;
